# Generated by Django 3.2.8 on 2021-12-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_cidade_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='usuario',
        ),
    ]
